DROP TABLE ISSUE_REPLY;

CREATE TABLE ISSUE_REPLY(ISSUE_NUM NUMBER REFERENCES PRJ_ISSUE(ISSUE_NUM) ON DELETE CASCADE,
USER_NICKNAME VARCHAR2(100),
REPLY_CONTENT VARCHAR2(4000),
REPLY_DATE_CREATE DATE);

SELECT * FROM ISSUE_REPLY;

SELECT * FROM ISSUE_REPLY WHERE ISSUE_NUM = 43;