DROP
	TABLE
		PRJ_ISSUE;

DROP
	SEQUENCE ISSUESEQ;

CREATE
	SEQUENCE ISSUESEQ;

CREATE
	TABLE
		PRJ_ISSUE(ISSUE_NUM NUMBER PRIMARY KEY,
		PRJ_NUM NUMBER REFERENCES PRJ_INFO(PRJ_NUM),
		BOARD_NUM NUMBER REFERENCES PRJ_BOARD(BOARD_NUM),
		ISSUE_TITLE VARCHAR2(500) NOT NULL,
		ISSUE_CONTENT VARCHAR2(4000),
		ISSUE_CHARGE VARCHAR2(100),
		ISSUE_PRIORITY VARCHAR2(50) NOT NULL,
		ISSUE_DEADLINE DATE,
		ISSUE_PARENT NUMBER,
		ISSUE_DATE_CREATE DATE NOT NULL,
		ISSUE_DATE_UPDATE DATE,
		ISSUE_DEL VARCHAR2(2) NOT NULL,
		CONSTRAINT DEL_CHK CHECK (ISSUE_DEL IN('Y',
		'N')),
		CONSTRAINT PRIORITY CHECK (ISSUE_PRIORITY IN('VERYHIGH',
		'HIGH',
		'MEDIUM',
		'LOW',
		'VERYLOW')) );

SELECT * FROM PRJ_ISSUE;

DELETE FROM PRJ_ISSUE;