DROP
	TABLE
		PRJ_ISSUE;

DROP
	SEQUENCE ISSUESEQ;

CREATE
	SEQUENCE ISSUESEQ;

CREATE
	TABLE
		PRJ_ISSUE(ISSUE_NUM NUMBER PRIMARY KEY,
		PRJ_NUM NUMBER REFERENCES PRJ_INFO(PRJ_NUM),
		BOARD_NUM NUMBER REFERENCES PRJ_BOARD(BOARD_NUM),
		ISSUE_TITLE VARCHAR2(500) NOT NULL,
		ISSUE_CONTENT VARCHAR2(4000),
		ISSUE_REQUIRE NUMBER, --요구인원
		ISSUE_CHARGE VARCHAR2(100), --책임자
		ISSUE_PRIORITY VARCHAR2(50) NOT NULL, --우선순위
		ISSUE_DEADLINE DATE, --마감일자
		ISSUE_PARENT NUMBER, --하위 작업
		ISSUE_DATE_CREATE DATE NOT NULL,
		ISSUE_DATE_START DATE,
		ISSUE_DEL VARCHAR2(2) NOT NULL, --이슈 삭제 여부
		CONSTRAINT DEL_CHK CHECK (ISSUE_DEL IN('Y',
		'N')),
		CONSTRAINT PRIORITY CHECK (ISSUE_PRIORITY IN('VERYHIGH',
		'HIGH',
		'MEDIUM',
		'LOW',
		'VERYLOW')) );

SELECT * FROM PRJ_ISSUE;

INSERT INTO PRJ_ISSUE VALUES(
	ISSUESEQ.NEXTVAL, 1,1, '문제가 생겼습니다.', '달력 일자로 연속되게 어떻게 하나요?', 5, '최준연', 'VERYHIGH', SYSDATE, 2,SYSDATE,SYSDATE,'N'
);