DROP
	TABLE
		PRJ_BOARD;

DROP
	SEQUENCE BOARDSEQ;

CREATE
	SEQUENCE BOARDSEQ;

CREATE
	TABLE
		PRJ_BOARD(BOARD_NUM NUMBER PRIMARY KEY,
		PRJ_NUM NUMBER REFERENCES PRJ_INFO(PRJ_NUM),
		BOARD_TITLE VARCHAR2(100) NOT NULL);

SELECT * FROM PRJ_BOARD;

SELECT * FROM PRJ_BOARD WHERE PRJ_NUM = 44;