DROP
	TABLE
		PRJ_ISSUE;

DROP
	SEQUENCE ISSUESEQ;

CREATE
	SEQUENCE ISSUESEQ;

CREATE
	TABLE
		PRJ_ISSUE(ISSUE_NUM NUMBER PRIMARY KEY,
		PRJ_NUM NUMBER REFERENCES PRJ_INFO(PRJ_NUM) ON
		DELETE
			CASCADE,
			BOARD_NUM NUMBER REFERENCES PRJ_BOARD(BOARD_NUM) ON
			DELETE
				CASCADE,
				ISSUE_TITLE VARCHAR2(500) NOT NULL,
				ISSUE_CONTENT VARCHAR2(4000),
				ISSUE_CHARGE VARCHAR2(100),
				ISSUE_PRIORITY VARCHAR2(50) NOT NULL,
				ISSUE_DEADLINE DATE,
				ISSUE_PARENT NUMBER,
				ISSUE_DATE_CREATE DATE NOT NULL,
				ISSUE_DATE_UPDATE DATE,
				ISSUE_DEL VARCHAR2(2) NOT NULL,
				CONSTRAINT DEL_CHK CHECK (ISSUE_DEL IN('Y',
				'N')),
				CONSTRAINT PRIORITY CHECK (ISSUE_PRIORITY IN('VERYHIGH',
				'HIGH',
				'MEDIUM',
				'LOW',
				'VERYLOW')) );

SELECT
	USER_NICKNAME
FROM
	USER_INFO
WHERE
	USER_NUM IN (
		SELECT USER_NUM
	FROM
		PRJ_IN_USER
	WHERE
		PRJ_NUM = 1);


	
	SELECT
		*
	FROM
		PRJ_ISSUE;

UPDATE
	PRJ_ISSUE
SET
	ISSUE_DATE_CREATE = '2020-12-12',
	ISSUE_DEADLINE = '2019-07-19'
WHERE
	ISSUE_NUM = 17;

INSERT
	INTO
		PRJ_ISSUE(ISSUE_NUM,
		PRJ_NUM,
		BOARD_NUM,
		ISSUE_TITLE,
		ISSUE_PRIORITY,
		ISSUE_DATE_CREATE,
		ISSUE_DEL,
		ISSUE_DEADLINE)
	VALUES(ISSUESEQ.NEXTVAL,
	1,
	1,
	1,
	'MEDIUM',
	(
		SELECT ADD_MONTHS(SYSDATE, 11)
	FROM
		DUAL),
	'N',
	(
		SELECT SYSDATE + 7
	FROM
		DUAL));

DELETE
FROM
	PRJ_ISSUE;
		PRJ_NUM NUMBER REFERENCES PRJ_INFO(PRJ_NUM) ON DELETE CASCADE,
		BOARD_NUM NUMBER REFERENCES PRJ_BOARD(BOARD_NUM) ON DELETE CASCADE,
		ISSUE_TITLE VARCHAR2(500) NOT NULL,
		ISSUE_CONTENT VARCHAR2(4000),
		ISSUE_CHARGE VARCHAR2(100),
		ISSUE_PRIORITY VARCHAR2(50) NOT NULL,
		ISSUE_DEADLINE DATE,
		ISSUE_PARENT NUMBER,
		ISSUE_DATE_CREATE DATE NOT NULL,
		ISSUE_DATE_UPDATE DATE,
		ISSUE_DEL VARCHAR2(2) NOT NULL,
		CONSTRAINT DEL_CHK CHECK (ISSUE_DEL IN('Y',
		'N')),
		CONSTRAINT PRIORITY CHECK (ISSUE_PRIORITY IN('VERYHIGH',
		'HIGH',
		'MEDIUM',
		'LOW',
		'VERYLOW')) );

SELECT * FROM PRJ_ISSUE;

DELETE FROM PRJ_ISSUE;
=======
DELETE FROM PRJ_ISSUE;
